accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Додати URL авторизації за замовчуванням
    path('', include('django.contrib.auth.urls')),
    # Сторінка реєстрації
    path('register/', views.register, name='register'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Головна сторінка
    path('', views.index, name='index'),
    # Сторінка зі списком усіх тем
    path('topics/', views.topics, name='topics'),
    # Сторінка з информацією за окремою темою
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Сторінка для додавання нової теми
    path('new_topic/', views.new_topic, name='new_topic'),
    # Сторінка для додавання нового допису
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Cторінка для редагування допису
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Topic(models.Model):
    """Тема, яку вивчає користувач."""

    text = models.CharField(max_length=255, verbose_name='Назва теми')
    date_added = models.DateTimeField(auto_now_add=True, verbose_name='Створено')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null = True, verbose_name="Власник")

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Теми'
        

    def __str__(self):
        return self.text
    
class Entry(models.Model):
    """Допис за темами"""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name='Тема')
    text = models.TextField(verbose_name='Текст')
    date_added = models.DateTimeField(auto_now_add=True, verbose_name='Створено')

    class Meta:
        verbose_name = 'Допис'
        verbose_name_plural = 'Дописи'
        
    def __str__(self):
        if len(self.text) <= 50:
            return self.text
        else:
            return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
        

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render

# Create your views here.

def register(request):
    """Реєструє нового користувача"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
    
    context = {'form': form}
    return render(request, 'accounts/register.html', context)

learning_logs/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render

from .models import Topic
from .models import Entry
from .forms import TopicForm
from .forms import EntryForm

# Create your views here.

def index(request):
    """Головна сторінка застосунку"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Виводе список тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Виводе одну тему та всі її дописи"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {
        'topic': topic,
        'entries': entries,
    }
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Додає нову тему"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Додає новий допис до визначеної теми"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context = {
        'topic': topic,
        'form': form
    }
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редагує існуючий допис"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

accounts/templates/accounts/register.html
{% extends "learning_logs/base.html" %}
{% block content %}

  <form action="{% url 'accounts:register' %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button type="submit">Реєстрація</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Learning Log</title>
</head>
<body>
  <h1>
    <a href="{% url 'learning_logs:index' %}">Журнал навчання</a> |
    <a href="{% url 'learning_logs:topics' %}">Теми</a> |
    {% if user.is_authenticated %}
      {{ user.username }}
    {% else %}
      <a href="{% url 'accounts:login' %}">Вхід</a> |
      <a href="{% url 'accounts:register' %}">Реєстрація</a>
    {% endif %}
  </h1>
  {% block content %}{% endblock content %}

  {% if user.is_authenticated %}
    <hr>
    <form action="{% url 'accounts:logout' %}" method="post">
      {% csrf_token %}
      <button type="submit">Вихід</button>
    </form>
  {% endif %}
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </h2>

  <h3>Редагування допису</h3>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберегти допис</button>
  </form>
{% endblock content %}
  

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Журнал навчання допомагає Вам відслідковувати ваші успіхи у вивченні будь-якої теми.</p>
{% endblock content%}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </h2>

  <h3>Новий допис до теми</h3>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Новий допис</button>
  </form>
{% endblock content %}
  

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2>Додати тему</h2>

  <form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Додати тему</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2>Тема: {{ topic }}</h2>

  <h3>Дописи:</h3>
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Додати новий допис</a>
  </p>  
  
  <ul>
    {% for entry in entries %}
      <li>
        <p>{{ entry.date_added|date:"d.m.Y H:i" }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <p>
          <a href="{% url 'learning_logs:edit_entry' entry.id %}">Редагувати</a>
        </p> 
      </li>
    {% empty %}
      <li>До теми ще не додано дописів.</li>
    {% endfor %}
  </ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p> Tevb</p>
  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>

        </li>
    {% empty %}
        <li>Жодної теми ще не було додано.</li>
    {% endfor %}
    </ul>

    <a href="{% url 'learning_logs:new_topic' %}">Додати нову тему</a>
{% endblock content %}
        